name: QuestionReg
main: idv.xfl03.quesreg.bukkitapi.QuestionReg
author: xfl03
version: 1.0.0
description: Question Reg
website: https://github.com/xfl03
commands:
   questionreg:
      description: Question Register Plugin
      aliases: [qr,qreg]
      usage: /<command> <arg1> <arg2>